sonar.projectKey=erik2259_Escaneo-SAST-DAST-de-una-mini-aplicacion
sonar.organization=erik2259

# Esto le dice a SonarCloud qué analizar
sonar.sources=.
sonar.python.version=3
sonar.language=py
sonar.sourceEncoding=UTF-8